Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder "..", "/vagrant" #, mount_options: ["dmode=700,fmode=600"]

    config.vm.provider "virtualbox" do |vb|
        # Enable nested virtualization:
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

        # Increase the size of the VM, since it will have nested VMs:
        vb.cpus = 4
        vb.memory = 8192
    end

    config.vm.provision "shell" do |shell|
        shell.inline = <<-SHELL
            set -euxo pipefail

            # Prevent any interaction from apt:
            export DEBIAN_FRONTEND=noninteractive

            apt-get update

            apt-get install -y virtualbox

            apt-get install -y python3-pip
            pip install ansible

            apt-get install -y vagrant
            
            pip install "molecule[vagrant]"
            pip install molecule-vagrant
            pip install 'molecule-plugins[vagrant]'
            pip install pytest-testinfra
        SHELL
    end
  end