---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
